site_name: wiki
site_url: https://udonrobo.github.io/wiki/

repo_url: https://github.com/udonrobo/wiki
repo_name: udonrobo/wiki

copyright: udonrobo © 2024

nav:
  - ホーム: index.md
  - 部品の制御方法:
    - アクチュエータ:
        - DCモーター: actuator/motor/index.md
        - ロボマスモーター: actuator/robomaster_motor/index.md
        - サーボモーター: actuator/servo/index.md
        - ソレノイド: actuator/solenoid/index.md
        - 電磁弁: actuator/valve/index.md
    - センサ:
        - スイッチ: sensor/switch/index.md
        - ロータリーエンコーダー: sensor/rotary_encoder/index.md
        - BNO055(ジャイロセンサ): sensor/bno055/index.md
  # - 通信:
  #     - コントローラー: communication/controller/index.md
  - 基板:
      - JLCPCB 発注手順: pcb/jlcpcb/index.md
  - 制御班勉強会:
      - はじめに: practice/index.md
      - コマンド: practice/command/index.md
      - Git・GitHub: practice/git/index.md
      - C++: practice/cpp/index.md
      - モーターとクラス: practice/motor/index.md
      - ファイル分割: practice/file_splitting/index.md
      - UdonLibraryの使い方: practice/udon_library/index.md
      - オムニを動かそう: practice/omni/index.md
      - 通信について: practice/communication/index.md

theme:
  name: material
  language: ja
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
