site_name: wiki
site_url: https://udonrobo.github.io/wiki/

repo_url: https://github.com/udonrobo/wiki
repo_name: udonrobo/wiki

nav:
  - ホーム: index.md
  - 制御班勉強会:
      - はじめに: practice/index.md
      - コマンド: practice/command/index.md
      - Git・GitHub: practice/git/index.md
      - C++: practice/cpp/index.md
      - モーターとクラス: practice/motor/index.md
      - ファイル分割: practice/file_splitting/index.md
      - UdonLibraryの使い方: practice/udon_library/index.md
      - 通信について: practice/communication/index.md
      - オムニを動かそう: practice/omni/index.md
      - ロボマスモーター: practice/robomaster_motor/index.md

theme:
  name: material
  language: ja
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # Default palette
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
